# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
      - name: setup git auth
        env:
          email: 'jefteamorim@gmail.com'
          username: 'JefteCosta'
          access_token: TOKEN
          NODE_ENV: 'production'
          VUE_APP_SERVER: https://wtechnology.tk
        run: |
          git config --global credential.helper store
          echo "https://${access_token}:x-oauth-basic@github.com" > ~/.git-credentials
          git config --global user.email $email
          git config --global user.name $username
      - name: deploy to Prodution
        run: |
          git clone https://github.com/JefteCosta/comment-api.git
          git checkout develop
          git marge main
          git push main
